name: Build

on:
  push:
    branches: [ "buildtest" ]
  pull_request:
    branches: [ "buildtest" ]

permissions:
  contents: read

env:
  # settings > CI/CD > Variables instead
  BUILD_NAME: usgeditor
  # manual trigger Build Assetbundle parameters
  BUILD_AB: "false"
  BUILD_WIN_AB: "false"
  BUILD_IOS_AB: "false"
  BUILD_ANDROID_AB: "false"
  BUILD_ALL_AB: "false"
  # manual trigger Build Launcher parameters
  TEST_WIN: "false"
  TEST_ANDROID: "false"
  TEST_IOS: "false"
  TEST_LAUNCHERS: "false" # include win android iOS platforms
  # docker image
  UNITY_VERSION: "2020.3.15f2"
  UNITY_ACTIVATION_FILE: ./unity3d.alf
  IMAGE: unityci/editor # https://hub.docker.com/r/unityci/editor
  IMAGE_VERSION: 1 # This will automatically use latest v1.x.x, see https://github.com/game-ci/docker/releases
  UNITY_DIR: $CI_PROJECT_DIR/USGEditor # this needs to be an absolute path. Defaults to the root of your tree.
  # You can expose this in Unity via Application.version 
  VERSION_NUMBER_VAR: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_JOB_ID
  VERSION_BUILD_VAR: $CI_PIPELINE_IID

jobs:
  set-container-image-name:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    steps:
    - id: set_image
      run: 
        echo "image=${{ env.IMAGE }}:${{ env.UNITY_VERSION }}-windows-mono-${{ env.IMAGE_VERSION}}" >> $GITHUB_OUTPUT
  build-assetbundle-StandaloneWindows64mono:
    runs-on: ubuntu-latest 
    needs: set-container-image-name
    container: 
      image: ${{ needs.set_image.outputs.image }}
    env:
      BUILD_TARGET: StandaloneWindows64
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: unity_defaults and unity_before_script
      run: |
        chmod +x ./ci/before_script.sh && ./ci/before_script.sh
        echo "before_script"
        chmod +x ./ci/build_assetbundle.sh && ./ci/build_assetbundle.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-assetbundle-StandaloneWindows64mono
        path: ${{ env.UNITY_DIR }}/BuildsAssetbundle/    

