name: Linters

on:
  pull_request: {}
  push: {}

jobs:
  gitlint:
    runs-on: ubuntu-latest
    name: GitLint
    steps:
      - name: Lint commits, branches, and pull requests
        uses: aschbacd/gitlint-action@v1.1.1
        with:
          re-commit-message-subject: ^(\[[A-Z]+\-[0-9]+\] )?[A-Z].*((?!\.).)$
          re-pull-request-title: ^(\[[A-Z]+\-[0-9]+\] )?[A-Z].*((?!\.).)$
