name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  Build-UltraSound:
    name: Build-UltraSound
    runs-on: ubuntu
    steps:
    - name: checkout
      uses: actions/checkout@v3  
